blank_issues_enabled: false
contact_links:
  - name: suyu Discussions
    url: https://github.com/orgs/suyu-emu/discussions
    about: If you are experiencing an issue with suyu, and you need tech support, or if you have a general question, try asking in the official suyu Discussions linked here. Piracy is not allowed.
